[font.normal]
family = "JetBrainsMono Nerd Font"


[general]
# import = ["~/.config/alacritty/catppuccin-macchiato.toml"]
import = ["~/.config/alacritty/kanagawa-wave.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.65
startup_mode = "SimpleFullscreen"

[font]
size = 16

[keyboard]
bindings = [
  # Toggle Simple Fullscreen (macOS only)
  { key = "F", mods = "Control|Shift", action = "ToggleSimpleFullscreen" },
]
