[font.normal]
family = "JetBrainsMono Nerd Font"


[general]
import = ["~/.config/alacritty/tokyonight-storm.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 1                       #0.75
startup_mode = "SimpleFullscreen"

[font]
size = 16
