# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  	'exec-and-forget sketchybar',
  	'exec-and-forget borders'
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 20
    inner.vertical =   20
    outer.left =       20
    outer.bottom =     20
    outer.top =        16
    outer.right =      20

# Application workspace bindings
# Bind Alacritty to workspace 1
[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace 1'

# Bind Chrome to workspace 2
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 2'

# Bind Discord to workspace 3
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 3'

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
# NOTE: These bindings use hyper key (right cmd mapped to cmd+ctrl+alt+shift)
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # Layout commands
    cmd-ctrl-alt-shift-slash = 'layout tiles horizontal vertical'
    cmd-ctrl-alt-shift-comma = 'layout accordion horizontal vertical'

    # Focus commands (vim-style navigation)
    cmd-ctrl-alt-shift-h = 'focus left'
    cmd-ctrl-alt-shift-j = 'focus down'
    cmd-ctrl-alt-shift-k = 'focus up'
    cmd-ctrl-alt-shift-l = 'focus right'

    # Move windows 
    cmd-ctrl-alt-shift-y = 'move left'    # y = left of hjkl
    cmd-ctrl-alt-shift-u = 'move down'    # u = down 
    cmd-ctrl-alt-shift-i = 'move up'      # i = up
    cmd-ctrl-alt-shift-o = 'move right'   # o = right of hjkl

    # Resize commands
    cmd-ctrl-alt-shift-minus = 'resize smart -50'
    cmd-ctrl-alt-shift-equal = 'resize smart +50'

    # Workspace navigation
    cmd-ctrl-alt-shift-1 = 'workspace 1'
    cmd-ctrl-alt-shift-2 = 'workspace 2'
    cmd-ctrl-alt-shift-3 = 'workspace 3'
    cmd-ctrl-alt-shift-4 = 'workspace 4'
    cmd-ctrl-alt-shift-5 = 'workspace 5'
    cmd-ctrl-alt-shift-6 = 'workspace 6'
    cmd-ctrl-alt-shift-7 = 'workspace 7'
    cmd-ctrl-alt-shift-8 = 'workspace 8'
    cmd-ctrl-alt-shift-9 = 'workspace 9'

    # Move window to workspace (using q,w,e,r,t for easy access)
    cmd-ctrl-alt-shift-q = 'move-node-to-workspace 1'
    cmd-ctrl-alt-shift-w = 'move-node-to-workspace 2'
    cmd-ctrl-alt-shift-e = 'move-node-to-workspace 3'
    cmd-ctrl-alt-shift-r = 'move-node-to-workspace 4'
    cmd-ctrl-alt-shift-t = 'move-node-to-workspace 5'
    cmd-ctrl-alt-shift-a = 'move-node-to-workspace 6'
    cmd-ctrl-alt-shift-s = 'move-node-to-workspace 7'
    cmd-ctrl-alt-shift-d = 'move-node-to-workspace 8'
    cmd-ctrl-alt-shift-f = 'move-node-to-workspace 9'

    # Workspace back-and-forth and monitor switching
    cmd-ctrl-alt-shift-tab = 'workspace-back-and-forth'
    cmd-ctrl-alt-shift-space = 'move-workspace-to-monitor --wrap-around next'

    # Application launchers
    cmd-ctrl-alt-shift-c = 'exec-and-forget open -n /Applications/Alacritty.app'
    cmd-ctrl-alt-shift-b = 'exec-and-forget open -n /Applications/Google\ Chrome.app'
    cmd-ctrl-alt-shift-g = 'exec-and-forget open -n /Applications/Discord.app'

    # Service mode
    cmd-ctrl-alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    # Join commands (vim-style)
    h = ['join-with left', 'mode main']
    j = ['join-with down', 'mode main']
    k = ['join-with up', 'mode main']
    l = ['join-with right', 'mode main']

    # Volume controls
    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']
