services:
  nginx:
    image: nginx:alpine
    container_name: master_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - pf4_network

networks:
  pf4_network:
    external: true
