- name: Clone Shenfiles Repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ home }}/shenfiles"
    force: yes
    update: yes

- name: Create Config Directory
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ home }}/.config/nvim"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Link Dotfiles using GNU Stow
  become: yes
  become_user: "{{ user }}"
  shell: "stow -v -t {{ home }} ."
  args:
    chdir: "{{ home }}/shenfiles/server/dotfiles"
  register: stow_output
  changed_when: "'LINK' in stow_output.stderr or 'UNLINK' in stow_output.stderr"
